### ISSUE TITLE
Control Panel Viewing slow/unresponsive with lots of database rows

### ISSUE THREAD

**Issue by green-plastic** [putyourlightson/craft-entry-count#11]
I have ~260,000 rows for Entry Count and the CP template tries to load all the entries, which then doesn't load.

This is the same for Entry Count and Entry Count Plus (Craft 2).

Thanks.

**Comment by putyourlightson** [comment]
That is quite a lot of entries. To make it work will require some UI changes, specifically adding pagination. I'm assuming that the plugin works otherwise on the front-end?

**Comment by green-plastic** [comment]
That's rows from the plus version you sold me. Plug in works fine other than trying to view counts in the CP.

**Comment by putyourlightson** [comment]
Ok, I'll address this when I have more time.

**Comment by green-plastic** [comment]
Thanks!
