### ISSUE TITLE
Entry Count with the {% paginate %} tag

### ISSUE THREAD

**Issue by tcherokee** [putyourlightson/craft-entry-count#14]
Is there a way to use the plugin with the {% paginate %} tag? So something like this

`{% paginate craft.entryCount.entries.all() as pageInfo, entries %}`

I tried this  tag, but got this error

`Argument 1 passed to craft\helpers\Template::paginateCriteria() must implement interface craft\elements\db\ElementQueryInterface, array given`

**Comment by putyourlightson** [comment]
Try it without the .all() at the end.

**Comment by tcherokee** [comment]
That worked :)

**Comment by putyourlightson** [comment]
Great!
