### ISSUE TITLE
I have added the plugin in my craft2 cms system and it doesn't show in plugin panel   

### ISSUE THREAD

**Issue by Hispanick** [putyourlightson/craft-entry-count#15]
I have added the plugin in my craft2 cms system and it doesn't show in plugin panel. Where i was wrong?

craft/plugins/entry-count

**Comment by putyourlightson** [comment]
Can you double check that you grabbed v1 of the plugin (for Craft2)?
https://github.com/putyourlightson/craft-entry-count/tree/v1
