### ISSUE TITLE
How to update count from another app (mobile)

### ISSUE THREAD

**Issue by arifje** [putyourlightson/craft-entry-count#17]
Hi,

We would like to update the count from our mobile app (native iOS/Android). Is there a way to accomplish this?

Thanks!

**Comment by putyourlightson** [comment]
How is your app pulling content from Craft? The entry count plugin doesn't have an API element to it but it's not a lot of work to add one.

**Comment by arifje** [comment]
We're currently pulling the content with some JSON feeds and are using a the Webservice addon for Expresion Engine. But we're migrating from EE to Craft 3 and there's no API/Webservice addon besides Elements API that we're only using for pulling entry content with JSON feeds.

Would be great if we can get some kind of safe API POST/GET function in this plugin! :-)

**Comment by putyourlightson** [comment]
It's not something I plan on adding but you could set this up rather easily using templates to fetch and increment the entry count using the existing twig tags. If it's something you would rather have built into the plugin then you can email me directly to discuss options.
