### ISSUE TITLE
Sort entries by views with Elements API?

### ISSUE THREAD

**Issue by arifje** [putyourlightson/craft-entry-count#19]
I am using Elements API to create a JSON feed with entries, but I really need to sort them by the number of views. Is this possible? 

Thanks!

**Comment by putyourlightson** [comment]
In v2 of the Element API you can use a custom [serializer](https://github.com/craftcms/element-api#serializer) which you could use to order the entries but it's far from a simple tweak. An easier way might be to add the entry count value to each entry with a transformer and then you'll be able to order the JSON feed after you receive it. As for ordering them beforehand, I'm not sure if there's an easy way.
