### ISSUE TITLE
Plugin produces no results

### ISSUE THREAD

**Issue by jacksoncool** [putyourlightson/craft-entry-count#21]
installed plugin via the store, and entries get counted (none listed in the admin). And no show up in templates. 

I'm using the following template code: 

{% set entries = craft.entryCount.entries.section('articles')
                              .limit(4)
                              .all() %}

                                  {% for entry in entries %}
                                    {% set count = craft.entryCount.count(entry.id)
                                     %}

                                <li>
                                  <a href="{{ entry.url }}">{{ entry.title }}</a>
                                </li>
                                {% endfor %}

**Comment by putyourlightson** [comment]
Try this first to ensure that counts are being stored in the control panel:

    {% set entry = craft.entries.one() %}

    {% do craft.entryCount.increment(entry.id) %}

    {{ craft.entryCount.count(entry.id) }}
