### ISSUE TITLE
New to Craft - Where Do 

### ISSUE THREAD

**Issue by Stefenyo** [putyourlightson/craft-entry-count#27]
So sorry for being the noob here but as the title say, I'm pretty new to craft and i'm having a bit of trouble implementing this. I have a structure with over 100 entries and I'm trying to implement this on the template that list those entries. So each entry will have a count next to it. 

Does the code go inside the loop, outside the loop, or the template that each entry links to ? 

I already have this in my code 
`{% set entries = craft.entries.section('drinks').orderBy('lft desc') %}`

**Comment by bencroker** [comment]
To display the entry count for each entry, you can put this inside the loop:
```twig
Title: {{ entry.title }}
Count: {{ craft.entryCount.count(entry.id) }}
```

**Comment by Stefenyo** [comment]
thank you
