### ISSUE TITLE
CP only shows enabled entries

### ISSUE THREAD

**Issue by stefanmf** [putyourlightson/craft-entry-count#29]
The CP only shows enabled entries. How about an option to also show disabled entries, or just all entries that have an entry count > 0?

**Comment by bencroker** [comment]
Thanks for the suggestion but there are no plans to add new features to this plugin, which is primarily for educational purposes. If you need new features then please consider using the [View Count plugin](https://plugins.craftcms.com/view-count) which is commercially supported.
