### ISSUE TITLE
Display count in column in standard list of entries

### ISSUE THREAD

**Issue by marijana** [putyourlightson/craft-entry-count#3]
Hi,

This is more of a feature request than an issue.
Would it be possible to make the plugin display count in a new column in standard list of entries in Craft admin?

Thanks!
Marijana

**Comment by putyourlightson** [comment]
that was working until Craft 2.5, i'll make a note to update the code

**Comment by jacobgraf** [comment]
Just curious if this will be tweaked to work with Craft 2.5+? Thanks!

**Comment by putyourlightson** [comment]
Craft 2.5 changed how this works and we will no longer be implementing.
