### ISSUE TITLE
How can I exclude one or more entries from the entries output?

### ISSUE THREAD

**Issue by charkdesign** [putyourlightson/craft-entry-count#30]
I am wanting to exclude one or more entries (by their entry ID) from the entries output. The output would be displaying a limited number of the most viewed entries (e.g. 6) but there may be cases where certain entries shouldn't be displayed and therefore would need to be excluded. Is this possible?

**Comment by bencroker** [comment]
It is not possible to selectively output entries on the plugin page in the CP. What you could perhaps do, is conditionally count entries in your front-end templates.
