### ISSUE TITLE
Craft CMS 4

### ISSUE THREAD

**Issue by mateostabio** [putyourlightson/craft-entry-count#31]
Hi, just checking if this will be compatible with Craft CMS 4?

I see there is a recent push that was called "Craft 4 version" but when I look at my site on the Craft 4 Update tab, I still see that this plugin has the status of "NOT READY".
![Screen Shot 2022-06-21 at 4 12 13 PM](https://user-images.githubusercontent.com/5912721/174889361-410fc786-aa52-4775-8f5c-07a8468955c0.png)

Thanks!

**Comment by bencroker** [comment]
That's correct, it is coming, I'll prioritise it to get the stable version out this week.

**Comment by bencroker** [comment]
Just release version 3.0.0.
