### ISSUE TITLE
Daily count?

### ISSUE THREAD

**Issue by green-plastic** [putyourlightson/craft-entry-count#4]
Any plans to add in a daily count for entries? A use case would be for having a most popular section of the last days entries.

I'm currently looking for something, and this plugin is the closest I've seen. If not, I'll try to extend your plugin.

**Comment by putyourlightson** [comment]
No plans to add this and it would require an extensive rewrite of the plugin. Send me an email though, I have something that may be of help to you.

**Comment by green-plastic** [comment]
Sounds good! I sent you an email a few moments ago.
