### ISSUE TITLE
Slow down the Page massiv

### ISSUE THREAD

**Issue by davidhellmann** [putyourlightson/craft-entry-count#6]
Any Idea about this Topic? When the Plugin is activated the loadtime is +2-3 seconds as if the plugin is disabled? :/ I've it on my Homepage for 30 posts they all get a +1 after each reload. Are this to much posts?

**Comment by davidhellmann** [comment]
It's the same problem when I've add the do snippet just on the detailpage. On the homepage, I just show the count it slow down the page also this 2-3 seconds :/

**Comment by putyourlightson** [comment]
Can you turn on dev mode and look for the calls to the entry count plugin in the log? Also some code would help to troubleshoot the issue...
