### ISSUE TITLE
How to stop fake increments on entry

### ISSUE THREAD

**Issue by zizther** [putyourlightson/craft-entry-count#8]
I am trying to find a way that stops fake entry counts from users just refreshing the page or visiting it multiple times on multiple machines.

What is the best way to not have the count increment on every page/entry refresh?
Is there some logic that can wrap around the increment call that checks for logged-in and not logged-in users making requests to the page?

**Comment by putyourlightson** [comment]
The Entry Count plugin is purposefully designed to count page refreshes and visits from multiple machines, so we don't see these as "fake" entry counts.

You can easily exclude the count incrementing for logged in users as follows:
~~~~
{% if currentUser %}
  {% do craft.entryCount.increment(entry.id) %}
{% endif %}
~~~~
