### ISSUE TITLE
How to get top 5 posts based on count?

### ISSUE THREAD

**Issue by cosmin-seviciu** [putyourlightson/craft-entry-count#9]
I am not that familiar with twig and craft, is it possible to get top 5 posts based on count? As far as I understand the count is in another table and i can not simply do 
`{% set entries = craft.entries({
    section:'instaBlog',
    limit:3,
    offset: 0,
    order: "count desc"
})%}`

**Comment by cosmin-seviciu** [comment]
After I posted this a saw a closed issue regarding this, sorry for repeating the question.
Thanks.

**Comment by putyourlightson** [comment]
Ok no problem.
